Migration table created successfully.
CreateUsersTable: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `username` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreatePagesTable: create table `pages` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `name` varchar(255) null, `slug` varchar(255) not null, `content` text not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePagesTable: alter table `pages` add unique `pages_slug_unique`(`slug`)
CreatePostsTable: create table `posts` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `slug` varchar(255) not null, `content` text not null, `category_id` int not null, `image` varchar(255) not null, `deleted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateCategoriesTable: create table `categories` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateProjetosTable: create table `projetos` (`id` int unsigned not null auto_increment primary key, `nome` varchar(255) not null, `dt_inicio` date not null, `dt_fim` date not null, `criado_por` varchar(255) not null, `modificado_por` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
PessoaFisicaTable: create table `pessoa_fisica` (`id` int unsigned not null auto_increment primary key, `nome` varchar(255) not null, `nome_adotado` varchar(255) null, `cpf` varchar(255) null, `dt_nascimento` date null, `criado_por` varchar(255) not null, `modificado_por` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
TipoContatoTable: create table `tipo_contato` (`id` int unsigned not null auto_increment primary key, `nome` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
ContatoTable: create table `contato` (`id` int unsigned not null auto_increment primary key, `valor` varchar(255) not null, `tipo_contato_id` int unsigned not null, `pessoa_fisica_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
ContatoTable: alter table `contato` add constraint `contato_tipo_contato_id_foreign` foreign key (`tipo_contato_id`) references `tipo_contato` (`id`)
ContatoTable: alter table `contato` add constraint `contato_pessoa_fisica_id_foreign` foreign key (`pessoa_fisica_id`) references `pessoa_fisica` (`id`)
CreateRolesTable: create table `roles` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `description` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateRoleUserTable: create table `role_user` (`id` int unsigned not null auto_increment primary key, `role_id` int unsigned not null, `user_id` int unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePfProjetoTable: create table `pf_projeto` (`id` int unsigned not null auto_increment primary key, `pessoa_fisica_id` int unsigned not null, `projeto_id` int unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePfProjetoTable: alter table `pf_projeto` add constraint `pf_projeto_pessoa_fisica_id_foreign` foreign key (`pessoa_fisica_id`) references `pessoa_fisica` (`id`)
CreatePfProjetoTable: alter table `pf_projeto` add constraint `pf_projeto_projeto_id_foreign` foreign key (`projeto_id`) references `projetos` (`id`)
